// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: log.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogAggregator_StreamLogs_FullMethodName = "/pb.LogAggregator/StreamLogs"
)

// LogAggregatorClient is the client API for LogAggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogAggregatorClient interface {
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogRequest, LogResponse], error)
}

type logAggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogAggregatorClient(cc grpc.ClientConnInterface) LogAggregatorClient {
	return &logAggregatorClient{cc}
}

func (c *logAggregatorClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogRequest, LogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogAggregator_ServiceDesc.Streams[0], LogAggregator_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogAggregator_StreamLogsClient = grpc.ClientStreamingClient[LogRequest, LogResponse]

// LogAggregatorServer is the server API for LogAggregator service.
// All implementations must embed UnimplementedLogAggregatorServer
// for forward compatibility.
type LogAggregatorServer interface {
	StreamLogs(grpc.ClientStreamingServer[LogRequest, LogResponse]) error
	mustEmbedUnimplementedLogAggregatorServer()
}

// UnimplementedLogAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogAggregatorServer struct{}

func (UnimplementedLogAggregatorServer) StreamLogs(grpc.ClientStreamingServer[LogRequest, LogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLogAggregatorServer) mustEmbedUnimplementedLogAggregatorServer() {}
func (UnimplementedLogAggregatorServer) testEmbeddedByValue()                       {}

// UnsafeLogAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogAggregatorServer will
// result in compilation errors.
type UnsafeLogAggregatorServer interface {
	mustEmbedUnimplementedLogAggregatorServer()
}

func RegisterLogAggregatorServer(s grpc.ServiceRegistrar, srv LogAggregatorServer) {
	// If the following call pancis, it indicates UnimplementedLogAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogAggregator_ServiceDesc, srv)
}

func _LogAggregator_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogAggregatorServer).StreamLogs(&grpc.GenericServerStream[LogRequest, LogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogAggregator_StreamLogsServer = grpc.ClientStreamingServer[LogRequest, LogResponse]

// LogAggregator_ServiceDesc is the grpc.ServiceDesc for LogAggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogAggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.LogAggregator",
	HandlerType: (*LogAggregatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LogAggregator_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "log.proto",
}
